apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: istio-sidecar-injector
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: istio-sidecar-injector-service-account
