{{- define "mixer_containers" }}
    spec:
      serviceAccountName: istio-mixer-service-account
      volumes:
      - name: istio-certs
        secret:
          secretName: istio.istio-mixer-service-account
          optional: true
    {{- if $.Values.nodeSelector }}
      nodeSelector:
{{ toYaml $.Values.nodeSelector | indent 8 }}
    {{- end }}
      containers:
      - name: mixer
        image: "{{ $.Values.global.hub }}/mixer:{{ $.Values.global.tag }}"
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        ports:
        - containerPort: 9091
        - containerPort: 9093
        - containerPort: 42422
        args:
          - --configStoreURL=k8s://
          - --configDefaultNamespace={{ $.Release.Namespace }}
          - --trace_zipkin_url=http://zipkin:9411/api/v1/spans
        resources:
{{ toYaml $.Values.resources | indent 12 }}
      - name: istio-proxy
        image: "{{ $.Values.global.hub }}/{{ $.Values.global.proxy.image }}:{{ $.Values.global.tag }}"
        imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
        ports:
        - containerPort: 15004
        args:
        - proxy
        - mixer
      {{- if $.Values.global.controlPlaneSecurityEnabled }}
        - --controlPlaneAuthPolicy
        - MUTUAL_TLS
        - --customConfigFile
        - /etc/istio/proxy/envoy_mixer_auth.json
      {{- else }}
        - --controlPlaneAuthPolicy
        - NONE
        - --customConfigFile
        - /etc/istio/proxy/envoy_mixer.json
      {{- end }}
        resources:
{{ toYaml $.Values.global.proxy.resources | indent 12 }}
        volumeMounts:
        - name: istio-certs
          mountPath: /etc/certs
          readOnly: true
{{- end }}


{{-  $mixers := list "policy" "telemetry" }}
{{- range $idx, $mname := $mixers }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-{{ $mname }}
  labels:
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release: {{ $.Release.Name }}
    istio: mixer
spec:
  replicas: {{ $.Values.replicaCount }}
  template:
    metadata:
      labels:
        istio: mixer
        istio-mixer-type: {{ $mname }}
      annotations:
        sidecar.istio.io/inject: "false"
{{- template "mixer_containers" $ }}

---
{{- end }} {{/* range */}}
