apiVersion: v1
kind: Service
metadata:
  name: istio-pilot
  labels:
    app: istio-pilot
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 15005
    name: https-discovery
  - port: 15007
    name: http-discovery
    targetPort: 15007
  - port: 15003
    name: http-old-discovery
  - port: 15010
    name: grpc-xds
  - port: 8080
    name: http-legacy-discovery
  - port: 9093
    name: http-monitoring
  - port: 443
    name: admission-webhook
  selector:
    istio: pilot
